# rolebinding `ksqldb-1` gives user `ksql` the role 
# `ResourceOwner` for all topics named with the prefix `app1_`
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ksqldb-1
  namespace: confluent
spec:
  principal:
    name: ksql
    type: user
  resourcePatterns:
  # The topics prefix is: `app1_`
  - name: app1_
    patternType: PREFIXED
    resourceType: Topic
  role: ResourceOwner