apiVersion: v1
items:
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-0
  spec:
    clustersScopeByIds:
      connectClusterId: confluent.connect  #<namespace>.<connect_cluster_name>
    principal:
      name: connect
      type: user
    role: SecurityAdmin
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-1
  spec:
    principal:
      name: connect
      type: user
    resourcePatterns:
    - name: confluent.connect #<namespace>.<connect_cluster_name>
      patternType: LITERAL
      resourceType: Group
    - name: confluent.connect- #<namespace>.<connect_cluster_name>-
      patternType: PREFIXED
      resourceType: Topic
    role: ResourceOwner
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-2
  spec:
    principal:
      name: connect
      type: user
    resourcePatterns:
    - name: _confluent-monitoring
      patternType: PREFIXED
      resourceType: Topic
    role: DeveloperWrite
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-controlcenter-0
  spec:
    principal:
      name: c3
      type: user
    role: SystemAdmin
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-ksqldb-0
  spec:
    clustersScopeByIds:
      ksqlClusterId: confluent.ksqldb_ #<namespace>.<ksql_cluster_name>_
    principal:
      name: ksql
      type: user
    resourcePatterns:
    - name: ksql-cluster
      patternType: LITERAL
      resourceType: KsqlCluster
    role: ResourceOwner
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-ksqldb-1
  spec:
    principal:
      name: ksql
      type: user
    resourcePatterns:
    - name: _confluent-ksql-confluent.ksqldb_ #_confluent-ksql-<namespace>.<ksql_cluster_name>_
      patternType: PREFIXED
      resourceType: Topic
    role: ResourceOwner
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-schemaregistry-0
  spec:
    clustersScopeByIds:
      schemaRegistryClusterId: id_schemaregistry_confluent  # id_<sr-name>.<namespace>
    principal:
      name: sr
      type: user
    role: SecurityAdmin
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-schemaregistry-1
  spec:
    principal:
      name: sr
      type: user
    resourcePatterns:
    - name: _confluent-license
      patternType: LITERAL
      resourceType: Topic
    - name: _schemas_schemaregistry_confluent # _schemas_<sr-name>.<namespace>
      patternType: LITERAL
      resourceType: Topic
    - name: id_schemaregistry_confluent # id_<sr-name>.<namespace>
      patternType: LITERAL
      resourceType: Group
    role: ResourceOwner
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
