---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudproducer
  namespace: destination
spec:
  serviceName: cloudproducer
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: cloudproducer
  template:
    metadata:
      labels:
        app: cloudproducer
    spec:
      containers:
      - name: cloudproducer
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic source-topic  \
            --record-size 1024 \
            --throughput 5 \
            --producer.config /mnt/source-kafka.properties \
            --num-records 100000
        volumeMounts:
        - name: source-kafka-properties
          mountPath: /mnt
      volumes:
        - name: source-kafka-properties # Create secret with name `kafka-client-config` with client configurations
          secret:
            secretName: source-kafka-client-config-secure
---
apiVersion: v1
kind: Service
metadata:
  name: cloudproducer
  namespace: destination
spec:
  clusterIP: None
