apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cloudtopic
  name: cloudtopic
spec:
  containers:
  - image: confluentinc/cp-kafka:latest
    name: cloudtopic
    command:
    - /bin/sh
    - -c
    - |
      kafka-topics --bootstrap-server <source-ccloud-endpoint:9092> \
        --command-config  /mnt/source-kafka.properties \
        --create \
        --partitions 3 \
        --replication-factor 3 \
        --topic source-topic \
        --if-not-exists
    volumeMounts:
    - name: source-kafka-properties
      mountPath: /mnt
  volumes:
    - name: source-kafka-properties # Create secret with name `kafka-client-config` with client configurations
      secret:
        secretName: source-kafka-client-config-secure
  dnsPolicy: ClusterFirst
  restartPolicy: Never

